DROP SEQUENCE EMPLOYEE_SEQ;
DROP SEQUENCE IMPORT_SEQ;
--DROP SEQUENCE MATERIAL_SEQ;
DROP SEQUENCE WAREHOUSE_SEQ;
DROP SEQUENCE LINE_ENV_DATA_T_SEQ;
DROP SEQUENCE LINE_MANAG_DATA_T_SEQ;
DROP SEQUENCE SHIPPING_SEQ;

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS PURGE;
DROP TABLE IMPORT CASCADE CONSTRAINTS PURGE;
DROP TABLE MATERIAL CASCADE CONSTRAINTS PURGE;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS PURGE;
DROP TABLE WAREHOUSE CASCADE CONSTRAINTS PURGE;
DROP TABLE LINE_ENV_DATA_T CASCADE CONSTRAINTS PURGE;
DROP TABLE LINE_MANAG_DATA_T CASCADE CONSTRAINTS PURGE;
DROP TABLE SHIPPING CASCADE CONSTRAINTS PURGE;