CREATE TABLE STUD_T(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL,
    AGE NUMBER NOT NULL,
    GENDER CHAR(1) NOT NULL,
    GRADE CHAR(8) NOT NULL,
    -- 제약조건
    CONSTRAINT GENDER_CHK CHECK(GENDER IN('M','F')),
    CONSTRAINT AGE_CHK CHECK (AGE>19),
    CONSTRAINT GRADE_CHK CHECK (GRADE IN('1학년','2학년','3학년','4학년'))
);

-- 추가
INSERT INTO stud_t (ID, NAME, AGE, GENDER, GRADE) VALUES(11113, '홍길동', 100, 'M', '2학년');
INSERT INTO stud_t (ID, NAME, AGE, GENDER, GRADE) VALUES(11115, '안중근', 100, 'M', '5학년');

-- 수정
UPDATE stud_t SET NAME='전우치' WHERE NAME='홍길동' AND ID=11114;

-- 삭제
DELETE FROM stud_t WHERE ID=11114;
-- 모든 데이터 삭제
DELETE FROM stud_t;

SELECT
    *
FROM stud_t;

DROP TABLE STUD_T;